from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.worksheet.datavalidation import DataValidation

OUT = Path(__file__).with_name('Beauty_Guild_UAT_Test_Pack.xlsx')
HEADERS = ['Test Case ID','Objective','Preconditions','Test Steps','Expected Result','Actual Result','Pass/Fail','Evidence / Notes']

J = {
 '01 Registration': [('REG-001','Create a new member account','New email available.','Register with name/email and follow activation email.','Catalyst user is created and activation email is received.'),('REG-002','Validate required fields','Registration page open.','Submit with required fields empty.','Missing fields are identified and no incomplete user is created.'),('REG-003','Prevent duplicate registration','Email already has an account.','Register using the existing email.','Clear error appears and no duplicate user is created.')],
 '02 Login Dashboard': [('LOG-001','Valid login','Activated user exists.','Enter valid credentials and submit.','User authenticates once and lands on Dashboard without a loop.'),('LOG-002','Invalid login','Login page open.','Enter incorrect password.','Clear error appears and user remains on login page.'),('LOG-003','Portal navigation','User is logged in.','Open Dashboard, Membership, GTi Courses, Accreditation and Insurance.','Items are clickable and active navigation is clear.')],
 '03 Membership': [('MEM-001','Show active membership','Test member has a current membership and future expiry date.','Open Membership.','Membership type, Current status and expiry date display.'),('MEM-002','No active membership','Test member has no current membership.','Start an accreditation and reach Summary.','Associate Membership is shown as a separate price line.'),('MEM-003','Active member pricing','Test member has a current membership.','View accreditation Summary.','Only the standard accreditation total is included.')],
 '04 New Accreditation': [('ACC-001','Start application','A test member is logged in.','Open Accreditation and select new application.','Wizard opens at Your details.'),('ACC-002','Required centre name','School Details is open.','Leave School Name blank and continue.','Continue remains unavailable until School Name is entered.'),('ACC-003','Prefill member data','Test member has existing contact and correspondence details.','Open Your details and Address.','Available member details prefill and remain editable.'),('ACC-004','Complete wizard','Required test information is available.','Complete all application steps.','Each step validates and progress works responsively.'),('ACC-005','Require tutor count','Tutors step is open.','Answer Yes to other tutors, confirm qualifications, and leave tutor count empty.','Inline guidance appears and continuation is blocked until a positive number is entered.')],
 '05 Address Map': [('ADR-001','Postcode lookup','Loqate configured.','Enter UK postcode and select result.','Address fields populate.'),('ADR-002','Manual address','Address step open.','Use manual entry and complete fields.','User can continue and values persist.'),('ADR-003','Geocode marker','Valid address entered.','Open map step.','Map loads with marker at resolved location.')],
 '06 Course Selection': [('CRS-001','Eligible courses','Test environment includes active GTI and ineligible courses.','Open Available accreditation courses.','Only eligible active GTI courses display.'),('CRS-002','Treatment groups','Eligible courses have treatment groups.','Review and expand course groups.','Courses are grouped by treatment group and easy to scan.'),('CRS-003','Course selection','Courses display.','Select several, deselect one, return to the step.','Selections persist accurately.')],
 '07 Summary Submission': [('SUB-001','Review summary','Required steps complete.','Inspect Summary sections.','Details, courses and the customer-visible total match the information entered.'),('SUB-002','Accept terms and submit','Terms unchecked.','Try Pay Now; accept terms; select Pay Now.','Payment is blocked until acceptance, then checkout begins once.'),('SUB-003','Visible application status','Application has been submitted but not paid.','Return to Accreditation.','The application appears once under Payment required and View summary opens it.'),('SUB-004','Prevent duplicate submission','The first request may be delayed.','Select Pay Now once and wait for a result.','The button shows progress and only one visible application remains available.')],
 '08 Stripe Payment': [('PAY-001','Open Checkout','An unpaid test application and Stripe test pricing are available.','Select Pay Now.','Stripe test Checkout opens with the same amount shown on Summary.'),('PAY-002','Verify pricing','Use one current member and one non-member test account.','Compare each Summary total with Stripe Checkout.','Current-member and membership-inclusive totals match on both screens.'),('PAY-003','Successful payment','Stripe test Checkout is open.','Use a Stripe test card and complete payment.','The user returns to the portal and the application no longer asks for a second payment after processing.'),('PAY-004','Cancel and retry','Stripe test Checkout is open.','Cancel, return to Accreditation and select Pay Now again.','The same application remains available and checkout can be reopened without a duplicate application.')],
 '09 Awaiting Payment': [('AWP-001','Show awaiting payment','A test application is awaiting payment.','Open Accreditation.','Application appears once under Payment required.'),('AWP-002','Open summary','Awaiting application is listed.','Click the application or View summary.','The existing application opens at Summary while earlier steps remain unavailable.'),('AWP-003','Reuse payment route','Awaiting application exists.','Select Pay Now and wait; return and retry if required.','The existing checkout route or application is reused and the button shows progress.')],
 '10 Qualifications': [('QUA-001','Add first qualification','A submitted accreditation is available in the portal.','Add name, month/year, centre, delivery and assessment; save.','A success message appears and the qualification is listed as Pending review.'),('QUA-002','Validate completion date','Qualification form is open.','Leave month/year incomplete.','Save remains unavailable until a valid month and four-digit year are supplied.'),('QUA-003','Add multiple qualifications','First qualification is listed.','Add a second qualification.','Both qualifications remain listed and Add qualification remains available.'),('QUA-004','Show processing status','Application has no qualifications.','Save the first qualification and return to Accreditation.','The application visibly shows Qualifications received or an equivalent processing state.')],
 '11 School Portal': [('SCH-001','Open accredited school','A test member has one accredited centre.','Open Accreditation and select the centre.','Workspace shows the selected centre name, customer-friendly status and expiry.'),('SCH-002','Navigate school sections','School workspace is open.','Use Profile, Courses, Venues, Tutors and Qualifications.','Sections open and the active section is clear.'),('SCH-003','Manage multiple schools','Test member has two verified centres linked to separate accreditation records.','Return to Accreditation and open each centre in turn.','Centres list vertically and each workspace shows only the selected centre data.'),('SCH-004','Add a course','School workspace is open for an accredited centre.','Open Courses and review the Add course section below the accredited courses table.','Other available GTi courses are listed with a Get in touch action, without any duplicate top-level tab.'),('SCH-005','Responsive workspace','School workspace is open.','Narrow the browser window (or view on a mobile device) on Courses, Venues, Tutors and Qualifications.','Page content stays within the screen width with no horizontal page scrolling; wide tables scroll only within their own panel.')],
 '12 Logout Return': [('OUT-001','Log out','User logged in.','Select logout.','Session clears and login page appears.'),('OUT-002','Prevent silent re-entry','User just logged out.','Refresh or use browser back.','User is not silently authenticated.'),('OUT-003','Log back in','User logged out with valid credentials.','Log in again.','User lands on Dashboard.')],
}

wb = Workbook(); ov = wb.active; ov.title = 'Overview'
ov.append(['Beauty Guild Portal - UAT Test Pack']); ov.merge_cells('A1:B1')
for row in [['Purpose','Journey-based customer UAT for visible Beauty Guild portal, address lookup and Stripe test-payment flows.'],['Environment','Catalyst Development / Stripe test mode'],['How to use','Run each journey in the portal, record Actual Result, select Pass/Fail/Blocked and attach evidence.'],['Test data','Use dedicated test members. Never use live payment cards or production credentials.'],['Scope','Validate only portal actions and visible outcomes. Back-office checks are completed separately by the implementation team.']]: ov.append(row)
ov.append([]); ov.append(['Journey','Test cases'])
for name,cases in J.items(): ov.append([name,len(cases)])

pink='E0007F'; dark='211A2C'
for name,cases in J.items():
    ws=wb.create_sheet(name); ws.append(HEADERS)
    for case in cases: ws.append([*case,'','Not Started',''])
    ws.freeze_panes='A2'; ws.auto_filter.ref=f'A1:H{ws.max_row}'; ws.sheet_view.showGridLines=False; ws.row_dimensions[1].height=32
    for cell in ws[1]: cell.fill=PatternFill('solid',fgColor=pink); cell.font=Font(color='FFFFFF',bold=True); cell.alignment=Alignment(wrap_text=True,vertical='center')
    for row in ws.iter_rows(min_row=2):
        for cell in row: cell.alignment=Alignment(wrap_text=True,vertical='top')
        ws.row_dimensions[row[0].row].height=65
    for col,width in zip('ABCDEFGH',[15,28,30,52,46,40,14,32]): ws.column_dimensions[col].width=width
    dv=DataValidation(type='list',formula1='"Not Started,Pass,Fail,Blocked,N/A"'); ws.add_data_validation(dv); dv.add(f'G2:G{ws.max_row}')

ov['A1'].fill=PatternFill('solid',fgColor=pink); ov['A1'].font=Font(color='FFFFFF',bold=True,size=16)
for cell in ov[8]: cell.fill=PatternFill('solid',fgColor=dark); cell.font=Font(color='FFFFFF',bold=True)
ov.column_dimensions['A'].width=28; ov.column_dimensions['B'].width=105; ov.sheet_view.showGridLines=False; ov.freeze_panes='A9'
wb.save(OUT); print(OUT)
